---
title: "taxonomy"
author: "Carl Boettiger"
date: "2020-07-21"
output: 
  github_document:
    df_print: tibble
---


```{r setup, message=F}
library(dplyr)
expert <- readRDS("../data/bet_expert.rds")
para <- readRDS("../data/bet_parataxonomist.rds")
sorting <- readRDS("../data/bet_sorting.rds")
```



```{r}

## NA scientificName.y means it wasn't pinned bc sorter was confident in ID, so we stick with that
## Otherwise, we go with the expert's decision.  
## IDs based on pinned taxonomy have an individualID, if ID comes only from sorting and wasn't pinned, individualID is NA.
taxonomy <-
  left_join(sorting, para, by = "subsampleID")  %>% 
  left_join(expert, by = "individualID") %>%
  mutate(taxonRank = ifelse(is.na(taxonRank), taxonRank.x, taxonRank),
         scientificName = ifelse(is.na(scientificName), scientificName.x, scientificName),
         taxonID = ifelse(is.na(taxonID), taxonID.x, taxonID),
         morphospeciesID =  ifelse(is.na(morphospeciesID), morphospeciesID.x, morphospeciesID)) %>%
  select(-ends_with(".x"), -ends_with(".y"))

## Use morphospecies if available for higher-rank-only classifications,
## Otherwise, binomialize the scientific name:
taxonomy <- taxonomy %>% 
  mutate(species = 
           ifelse(taxonRank %in% c("subgenus", "genus", "family", "order") & !is.na(morphospeciesID), 
                  morphospeciesID,
                  taxadb::clean_names(scientificName)
                  )
         )

## Beetles must be identified as carabids by both sorting table and the taxonomists (~3 non-Carabidae slip through in sorting)
beetles <- taxonomy %>% 
  filter(grepl("carabid", sampleType)) %>%
  filter(family == "Carabidae" | is.na(family))


beetles %>% count(species) # 822
beetles %>% count(taxonID) # 747
beetles %>% count(scientificName) # 747
```




This approach misses species ID'd by parataxomonists to a finer resolution but where we do not have those individualIDs in the expert table.  Most of these are 2013 and 2014 samples -- perhaps there was no expert ID step then?  The rest are more recent -- probably due to the 2 year latency on the expert data table?

```{r}
library(ggplot2)


para_id_only <- 
  left_join(sorting, para, by = "subsampleID")  %>% 
  left_join(expert, by = "individualID") %>% 
  filter(scientificName.x != scientificName.y, is.na(scientificName)) %>% 
  select(scientificName.x, taxonRank.x, scientificName.y, taxonRank.y, collectDate.x, scientificName, taxonRank) 

para_id_only %>% count(taxonRank.x) # 711 at family level
para_id_only %>% count(taxonRank.y) # only 5 at family level

para_id_only %>% ggplot(aes(collectDate.x)) + geom_histogram()
```




---------------




## Exploratory analyses





```{r}
no_pin <- anti_join(sorting, para, by = "subsampleID")
no_pin %>% filter(grepl("carabid", sampleType))  %>% count(taxonRank)
## 347 subsamples had beetle(s) that could not be ID'd to species level but were not pinned due to issues (e.g. too small, head missing, etc)
## Other not-pinned stuff ain't carabids (though a few pinned things turn out not to be carabids either...)
no_pin %>% filter(grepl("carabid", sampleType))  %>% filter(taxonRank %in% c("genus", "family"))



## Everything the experts ID to family has a specificEpithet.
taxonomy # 163,793
taxonomy  %>% filter(grepl("carabid", sampleType)) # 91,594
taxonomy  %>% filter(grepl("carabid", sampleType)) %>% count(taxonRank)
taxonomy %>% filter(grepl("carabid", sampleType), family != "Carabidae")  ## 41 aren't actually carabids




taxonomy %>% filter(grepl("carabid", sampleType)) %>% filter(taxonRank %in% c("subgenus", "genus", "family", "order")) %>% filter(!is.na(morphospeciesID)) # 2,306 have morphospeciesID
taxonomy %>% filter(grepl("carabid", sampleType)) %>% filter(taxonRank %in% c("subgenus", "genus", "family", "order")) %>% filter(is.na(morphospeciesID))  %>% count(taxonRank) # 1,715 do not

taxonomy %>% filter(family == "Carabidae")  # 41,705

taxonomy %>% filter(taxonRank %in% c("genus", "family"),  !is.na(morphospeciesID) ) # 1.9K
taxonomy %>% filter(taxonRank %in% c("genus", "family"),  is.na(morphospeciesID) )  # 1.7K

taxonomy %>%  filter(taxonRank %in% c("genus", "family"),  is.na(morphospeciesID) ) %>% filter(is.na(specificEpithet), family == "Carabidae")

```



```{r}
taxonomy %>% count(taxonRank)
## Some things identified as carabid family in sorting table aren't so, according to experts
taxonomy %>% filter(taxonRank %in% c("order", "phylum")) %>% select(scientificName, taxonRank, sampleType)
## Sometimes experts give two different ids to the same individual... probably a data entry problem?
expert %>% 
    group_by(individualID) %>% 
    filter(n_distinct(taxonID) > 1) %>% inner_join(expert) %>% 
  select(taxonID, taxonRank, scientificName, identifiedBy, identifiedDate, identificationQualifier, identificationReferences, scientificNameAuthorship, laboratoryName)
```


```{r}
A <- left_join(sorting, para, by = "subsampleID")  %>% 
  left_join(expert, by = "individualID") %>%
  filter(collectDate.x > as.Date("2017-01-01"))

## Only 260                                                                     
A %>% 
  filter(scientificName.x != scientificName.y) %>% 
  select(scientificName.x, taxonRank.x, scientificName.y, taxonRank.y, collectDate.x, scientificName, taxonRank)

## only 62
A %>% 
  filter(scientificName.x != scientificName.y, is.na(scientificName)) %>% 
  select(scientificName.x, taxonRank.x, scientificName.y, taxonRank.y, collectDate.x, scientificName, taxonRank)

## Only inverts / bycatch have no sci name in sample table.  
A %>% filter(is.na(scientificName.x)) %>% count(sampleType)


## ~ 4K                                                                
A %>% 
  filter(scientificName.x != scientificName) %>% 
  select(scientificName.x, taxonRank.x, scientificName.y, taxonRank.y, collectDate.x, scientificName, taxonRank)


## ~ 4K                                                                
A %>% 
  filter(scientificName.y != scientificName) %>% 
  select(scientificName.x, taxonRank.x, scientificName.y, taxonRank.y, collectDate.x, scientificName, taxonRank)



matches <- A %>% 
  filter(scientificName.x == scientificName.y) %>% pull(subsampleID)


A %>% filter(subsampleID != matches)   %>% 
  select(scientificName.x, taxonRank.x, scientificName.y, taxonRank.y, subsampleID) %>%
  filter(is.na(scientificName.y), !is.na(scientificName.x))


A %>% filter(subsampleID != matches)   %>% 
  select(scientificName.x, taxonRank.x, scientificName.y, taxonRank.y, subsampleID) %>%
  filter(is.na(scientificName.y), !is.na(scientificName.x)) %>% select(subsampleID) %>% inner_join(para)

```


Observe that `subsampleID` is unique in the sorting table, and is also found in the parataxonomy table (where it is not unique)

```{r}
sorting %>% count(subsampleID, sort = TRUE) # most frequent occurrence of any id is 1
```


This makes it a good key value to join on.  Note we *MUST NOT* join on the other columns, which can differ between the tables!


Observe that many species that could not be identified by the sorters have been identified by the para-taxonomists (and thus do not get a morpho-species assigned by the parataxonomist.)  Note that the `.x` indicates a column from the sorting table, and the `y` from the parataxonomy table.  

```{r}
taxa <- sorting %>% left_join(para, by = "subsampleID")
taxa %>% select(scientificName.x, scientificName.y, morphospeciesID.x, morphospeciesID.y, taxonID.x, taxonID.y, taxonRank.x, taxonRank.y)
```

How many species of carabid did the sorting step fail to classify to at least the species level?

```{r}
taxa %>% filter(grepl("carabid", sampleType)) %>% count(taxonRank.x)

unclassified <- taxa %>% 
  filter(grepl("carabid", sampleType), 
         taxonRank.x %in% c("family", "genus"))  %>% 
  mutate(year = lubridate::year(collectDate.x))
```

Let's focus on those 8,974 unclassified beetles. How many have the not been classified by the parataxonomists?

```{r}
unclassified  %>%  count(taxonRank.x)
```

Of those 8,974, 3397 still remain unclassified at the family level, and another 1874 at the genus level (so about 41% were successfully identified).  But also note that the parataxonomists have been able to at least give morphospecies ids to nearly all (only 100 have no `morphospeciesID.y`, though some of these have `morphospeciesID.x` so possibly the parataxonomist was questing that call).  Also note that almost all of those have "remarks" with what looks to be a guess for the species ID (i.e. could be a good proxy for the morphospecies)

```{r}
unclassified %>% filter(taxonRank.y == "family", is.na(morphospeciesID.y)) %>% select(scientificName.y, remarks.y, year)
```

Joining on the expert table maybe more of these can be identified. 





---------

Kari's example:

```{r}



## Adapted from Kari Norman (c) 2019
## https://github.com/martaajarzyna/temporalNEON/blob/5b428dacc68630ce23bd43f4393821c3d03f34be/data-raw/beetles_processing.Rmd


library(dplyr)


################# Taxonomy #####################################

# Take the bet_sorting table, join parataxonomy table by `subsampleID`, 
# Join that to expert table by `individualID`.  
# Prefer the higher-grade scientificName and taxonRank when available.
# Unpinned beetles in the same subsample inherit the ID of that subsample (??)
# Do nothing if the multiple experts disagree.  

# resulting table has all the columns of `sorting`, plus: `individualID` and `identificationSource`.
# identificationSource indicates if the scientificName was provided by the sorting (sort), parataxonomist (pin), or expert
# 
# The resulting table will likely have more rows than the input table, because multiple the subsample is now broken up into
# individuals always.  (be cautious of what this does to the individualCount column??)
resolve_taxonomy_kari <- function(sorting, para, expert){
  
  ## Join sorting by subsampleID, and prefer verdict of parataxonmist
  data_pin <-sorting %>% 
    left_join(
      para %>% select(subsampleID, individualID, taxonID, scientificName, taxonRank, morphospeciesID, identificationQualifier), 
      by = "subsampleID") %>%
    mutate_if(is.factor, as.character) %>%
    ## uses parataxonomy value unless it is an NA:
    mutate(taxonID = ifelse(is.na(taxonID.y), taxonID.x, taxonID.y)) %>%
    mutate(taxonRank = ifelse(is.na(taxonRank.y), taxonRank.x, taxonRank.y)) %>%
    mutate(scientificName = ifelse(is.na(scientificName.y), scientificName.x, scientificName.y)) %>%
    mutate(morphospeciesID = ifelse(is.na(morphospeciesID.y), morphospeciesID.x, morphospeciesID.y)) %>%
    mutate(identificationSource = ifelse(is.na(scientificName.y), "sort", "pin")) %>%
    mutate (identificationQualifier = ifelse(is.na(taxonID.y), identificationQualifier.x, identificationQualifier.y)) %>%
    select(-ends_with(".x"), -ends_with(".y"))
  
  
  #some subsamples weren't fully ID'd by the pinners, so we have to recover the unpinned-individuals
  lost_indv <- data_pin %>% 
    filter(!is.na(individualID)) %>%
    group_by(subsampleID, individualCount) %>%
    summarise(n_ided = n_distinct(individualID)) %>% 
    filter(n_ided < individualCount) %>%
    mutate(unidentifiedCount = individualCount - n_ided) %>%
    select(subsampleID, individualCount = unidentifiedCount) %>%
    left_join(sorting %>% select(-individualCount), by = "subsampleID") %>%
    mutate(identificationSource = "sort")
  #add unpinned-individuals back to the pinned id's, adjust the individual counts so pinned individuals have a count of 1
  data_pin <- data_pin %>%
    mutate(individualCount = ifelse(identificationSource == "sort", individualCount, 1)) %>%
    bind_rows(lost_indv)
  
  
  #There are ~10 individualID's for which experts ID'd more than one species (not all experts agreed), 
  ## we want to exclude those expert ID's as per Katie Levan's suggestion
  
  ## CB: More accurately, there are 3 IDs for which the same expert has given the same individualID two different scentificNames,
  ## and precisely 1 ID where two experts have assessed and appear to disagree.  (possibly a data entry problem, as in this case
  ## there are 2 records of the same expert giving the same ID as well)
  ex_expert_id <- expert %>% 
    group_by(individualID) %>% 
    filter(n_distinct(taxonID) > 1) %>% 
    pull(individualID)
  
  # Now add expert taxonomy info, where available
  data_expert <- left_join(data_pin, 
                           select(expert,
                                  individualID,taxonID,scientificName,taxonRank,identificationQualifier) %>%
                             filter(!individualID %in% ex_expert_id), #exclude ID's that have unresolved expert taxonomy
                           by = 'individualID', na_matches = "never") %>% distinct()
  
  # Replacement old taxon info with expert info, where available
  # NOTE - This is repetitive with the code snippet above, and if you want to do it this way you can just combine the calls into one chunk. BUT, you may
  #     want to do more than this, as it is *just* a replacement of IDs for individual beetles that an expert identified. If the expert identified
  #           a sample as COLSP6 instead of CARSP14, though, then all CARSP14 from that trap on that date should probably be updated to COLSP6…
  # CB: i.e. this fails to allow expert classification to trickle down to those unpinned beetles in the subsample(?)
  beetles_data <- data_expert %>%
    mutate_if(is.factor, as.character) %>%
    mutate(taxonID = ifelse(is.na(taxonID.y), taxonID.x, taxonID.y)) %>%
    mutate(taxonRank = ifelse(is.na(taxonRank.y), taxonRank.x, taxonRank.y)) %>%
    mutate(scientificName = ifelse(is.na(scientificName.y), scientificName.x, scientificName.y)) %>%
    mutate(identificationSource = ifelse(is.na(scientificName.y), identificationSource, "expert")) %>%
    mutate (identificationQualifier = ifelse(is.na(taxonID.y), identificationQualifier.x, identificationQualifier.y)) %>%
    select(-ends_with(".x"), -ends_with(".y"))
  
  beetles_data
}

## Hmm, why 2 distinct? 1 sci-name from the subsample was left not resolved below genus
## beetles_data %>% filter(uid == "98b5254e-0afc-4599-9c32-a0690085c6b9") %>% select(-individualID) %>% distinct() %>% select(scientificName, taxonRank)


## Hmm, confirm any count greater than 1 had no parataxonomy?
## beetles_data %>% filter(grepl("carabid", sampleType)) %>% count(individualCount, sort=TRUE) 
```
